adm_sekolah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('utama.urls')),
    path('siswa/', include('siswa.urls')),
    path('tagihan/', include('keuangan.urls')),
]

if settings.DEBUG :
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

keuangan/urls.py
from django.urls import path
from . import views

app_name = 'uang'
urlpatterns = [
    path('baru/', views.TagihanBaru.as_view(), name='tagihan-baru'),
    path('detail/<int:pk>/', views.TagihanDetail.as_view(), name='tagihan-detail'),
    path('delete/<int:pk>/', views.TagihanHapus.as_view(), name='tagihan-delete'),
    path('tanda-terima/', views.TandaTerimaAdd.as_view(), name='tanda-terima'),
    path('tanda-terima/edit/<int:pk>', views.TagihanEdit.as_view(), name='ttd-edit'),
    path('', views.TagihanView.as_view(), name='index'),
]

siswa/urls.py
from django.urls import path

from . import views

app_name = 'siswa'

urlpatterns = [
    path('baru/', views.SiswaAdd.as_view(), name='baru'),
    path('update/<int:pk>/', views.SiswaEdit.as_view(), name='update'),
    path('detail/<int:pk>/', views.SiswaDetail.as_view(), name='detail'),
    path('', views.SiswaList.as_view(), name='murid'),
]

keuangan/models.py
from django.db import models
from django.shortcuts import reverse

from utama.models import Semester, TahunPelajaran, Kelas, BiayaPendaftaran
from siswa.models import Siswa

# Create your models here.
class Tagihan(models.Model):
    murid = models.ForeignKey(Siswa, on_delete=models.CASCADE)
    tahun = models.ForeignKey(TahunPelajaran, on_delete=models.CASCADE)
    smester = models.ForeignKey(Semester, on_delete=models.CASCADE)
    untuk_kelas = models.ForeignKey(Kelas, on_delete=models.CASCADE)
    dari_semester_sebelumnya = models.IntegerField(default=0)
    status = models.CharField(max_length=20, choices=[('aktif', 'Aktif'), ('lunas', 'Lunas')], default='aktif')

    class Meta:
        ordering = ['murid', 'smester']
    
    def __str__(self):
        return self.murid.nama

    # yang belum dibayar
    def balance(self):
        harus_dibayar = self.total_harus_dibayar()
        dibayarkan = self.jumlah_total_dibayar()
        return harus_dibayar - dibayarkan
    
    def yang_harus_dibayar(self):
        items = InvoiceItem.objects.filter(tagihan=self)
        total = 0
        for item in items:
            total += int(item.jumlah.uang_masuk)
        return total
    
    def total_harus_dibayar(self):
        return self.dari_semester_sebelumnya + self.yang_harus_dibayar()
    
    def jumlah_total_dibayar(self):
        terima = TandaTerima.objects.filter(tagihan=self)
        jumlah = 0
        for tanda in terima:
            jumlah += tanda.jumlah_dibayar
        return jumlah
    
    def get_absolute_url(self):
        return reverse('uang:tagihan-detail', kwargs={'pk': self.id})

class InvoiceItem(models.Model):
    tagihan = models.ForeignKey(Tagihan, on_delete=models.CASCADE)
    deskripsi = models.CharField(max_length=100)
    jumlah = models.ForeignKey(BiayaPendaftaran, on_delete=models.CASCADE)

    def __str__(self):
        return self.deskripsi

class TandaTerima(models.Model):
    tagihan = models.ForeignKey(Tagihan, on_delete=models.CASCADE)
    jumlah_dibayar = models.IntegerField()
    tanggal_bayar = models.DateField()
    keterangan = models.CharField(max_length=125, null=True, blank=True)

    def __str__(self):
        return 'Tanda terima pada {}'.format(self.tagihan)

keuangan/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Tagihan, InvoiceItem, TandaTerima

InvoiceItemFormset = inlineformset_factory(
    Tagihan, InvoiceItem, fields=['deskripsi', 'jumlah'], extra=1, can_delete=True
)

TandaTerimaFormset = inlineformset_factory(
    Tagihan, TandaTerima, fields=[
        'jumlah_dibayar',
        'tanggal_bayar',
        'keterangan',
    ],
    widgets={
        'tanggal_bayar': forms.DateInput(
            attrs={
                'type': 'date'
            }
        )
    },
    extra=0, can_delete=True
)

class TandaTerimaForm(forms.ModelForm):
    class Meta:
        model = TandaTerima
        fields = ['jumlah_dibayar', 'tanggal_bayar', 'keterangan']
        widgets = {
            'tanggal_bayar': forms.DateInput(
                attrs={
                    'type': 'date'
                }
            )
        }

keuangan/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from siswa.models import Siswa
from .models import Tagihan, InvoiceItem, TandaTerima
from .forms import InvoiceItemFormset, TandaTerimaFormset, TandaTerimaForm
# Create your views here.
class TagihanBaru(LoginRequiredMixin, CreateView):
    model = Tagihan
    fields = '__all__'
    success_url = reverse_lazy('uang:index')

    def get_context_data(self, **kwargs):
        context = super(TagihanBaru, self).get_context_data(**kwargs)
        if self.request.POST:
            context['items'] = InvoiceItemFormset(
                self.request.POST, prefix='tagihanitem_set'
            )
        else:
            context['items'] = InvoiceItemFormset(
                prefix='tagihanitem_set'
            )
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['items']
        self.object = form.save()
        if self.object.id != None:
            if form.is_valid() and formset.is_valid():
                formset.instance = self.object
                formset.save()
        return super().form_valid(form)

class TagihanView(LoginRequiredMixin, ListView):
    queryset = Tagihan.objects.all()
    fields = '__all__'


class TagihanDetail(LoginRequiredMixin, DetailView):
    queryset = Tagihan.objects.all()
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(TagihanDetail, self).get_context_data(**kwargs)
        context['masuk'] = TandaTerima.objects.filter(tagihan=self.object)
        context['items'] = InvoiceItem.objects.filter(tagihan=self.object)
        return context

class TagihanHapus(LoginRequiredMixin, DeleteView):
    queryset = Tagihan.objects.all()
    success_url = reverse_lazy('uang:index')
    template_name = 'utama/confirm_delete.html'

class TagihanEdit(LoginRequiredMixin, UpdateView):
    queryset = Tagihan.objects.all()
    fields = ['status']

    def get_context_data(self, **kwargs):
        context = super(TagihanEdit, self).get_context_data(**kwargs)
        if self.request.POST:
            context['masuk'] = TandaTerimaFormset(self.request.POST, instance=self.object)
        else:
            context['masuk'] = TandaTerimaFormset(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['masuk']
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
        return super().form_valid(form)

class TandaTerimaAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = TandaTerima
    form_class = TandaTerimaForm
    success_url = reverse_lazy('uang:index')
    success_message = 'Pembayaran telah ditambahkan'

    def get_context_data(self, **kwargs):
        context = super(TandaTerimaAdd, self).get_context_data(**kwargs)
        tagihan = Tagihan.objects.get(pk=self.request.GET['pk'])
        context['tagihan'] = tagihan
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        tagihan = Tagihan.objects.get(pk=self.request.GET['pk'])
        obj.tagihan = tagihan
        obj.save()
        return redirect('uang:index')

templates/keuangan/tagihan_detail.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Tagihan untuk {{ object.murid }} {% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Tagihan</li>
<li><i class="fa fa-laptop"></i>Detail</li>
{% endblock breadcrumb %}

{% block heading %}
Pembayaran {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<div class="row">
    <div class="container">
        <div class="col">
            <h3>Detail Pembayaran untuk : {{ object }}</h3>
        </div>        
    </div>
    <div class="col-sm-4">        
        <h4>Tahun Pelajaran : {{ object.tahun }}</h4>
        <h4>Semester : {{ object.smester }}</h4>
        <h4>Kelas : {{ object.untuk_kelas }}</h4>
        <h4>Status :{{ object.status }}</h4>
        <hr>
        <div>
            <h4>Belum dibayar : Rp. {{ object.balance }}</h4>
        </div>
    </div>

    <div class="col-sm-8">
        <table class="table table-striped table-hover table-advance">
            <thead>
                <tr>
                    <th>S/N</th>
                    <th>Deskripsi</th>
                    <th>Jumlah Tagihan</th>
                </tr>
            </thead>
            <tbody>
                {% for tt in items %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ tt.deskripsi }}</td>
                    <td>Rp. {{ tt.jumlah }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="table-responsive">
    {% if object.status != 'lunas' %}
    <a href="{% url 'uang:tanda-terima' %}?pk={{ object.id }}" class="btn btn-primary"><i class="fa fa-plus"></i> Buat Tanda Terima Baru</a>
    <a href="#" class="btn btn-success"><i class="fa fa-plus"></i> Buat Semua Invoice</a>
    {% endif %}
    <h2>Riwayat Pembayaran</h2>
    <table id="tabelinv" class="table table-striped table-hover table-advance">
        <thead>
            <tr>
                <th>S/N</th>
                <th>Jumlah Bayar</th>
                <th>Tanggal Bayar</th>
                <th>Keterangan</th>
            </tr>
        </thead>
        <tbody>
            {% for tg in masuk %}
            <tr>
                <td>{{ forloop.counter }}</td>                
                <td>{{ tg.jumlah_dibayar }}</td>
                <td>{{ tg.tanggal_bayar }}</td>
                <td>{{ tg.keterangan }}</td>                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

templates/keuangan/tagihan_form.html
{% extends 'html.html' %}
{% load widget_tweaks %}

{% block page_title %}{% block title %}Buat Invoice Baru{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Tagihan</li>
<li><i class="fa fa-laptop"></i>Baru</li>
{% endblock breadcrumb %}

{% block heading %}
Tagihan Baru {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
    <form method="POST">
      {% csrf_token %}  
      <div class="row">
        <div class="col-sm-6">
          {% for field in form %}
          <div class="form-group">
            <label for="{{ field.auto_id }}">
              {{ field.label }}
              {% for error in field.errors %}
              <small id="{{ field.auto_id }}" class="text-danger">{{ error }}</small>
              {% endfor %}
            </label>
            <div class="form-group">
              {{ field | add_class:"form-control"}}
              {% if field.help_text %}
              <small>{{ field.help_text|safe }}</small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
        {% if items %}
        <div class="col-sm-6 callout callout-info">
          {{ items.management_form }}
          <div class="text-center">Biaya Masuk</div>
          {% for item in items %}
          <div class="form-group items-group">
            {{ item.id }}
            <div class="form-group"><strong>Fee Type</strong></div>
            <div class="form-group">{{ item.jumlah | add_class:"form-control"}}</div>
            <div class="form-group"><strong>Keterangan</strong></div>
            <div class="form-group">{{ item.deskripsi | add_class:"form-control"}}</div>
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    
      {% if object %}
      <div class="form-group">
        <h2>Tanda Terima</h2>
        <table class="table table-sm">
          {{ masuk.management_form }}
          <thead class="thead-light">
            <tr>
              <th>Uang Setoran</th>
              <th>Tanggal Bayar</th>
              <th>Keterangan</th>
              <th><i class="fa fa-trash"></i></th>
            </tr>
          </thead>
          <tbody>
            {% for ms in masuk %}
            {% for hidden in ms.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            <tr>
              {% for field in ms.visible_fields %}
              <td>{{ field | add_class:"form-control form-control-sm"}}</td>
              {% endfor %}
            </tr>
            {% endfor %}
    
          </tbody>
        </table>
      </div>
      {% endif %}
    
      <div class="form-group">
        <div class="col-lg-offset-0 col-lg-10">
          {% if object %}
          <input type="submit" class="btn btn-primary" value="Update Record"> <div class='btn btn-danger'><i class='fas fa-trash'></i><a href="{% url 'uang:tagihan-delete' pk=object.id %}">Delete</a></div>
          {% else %}
          <input type="submit" class="btn btn-primary" value="Add new invoice">
          {% endif %}
        </div>
      </div>
    </form>
<hr>
    
<script>
$(".items-group").formset(
  {
    prefix: '{{ items.prefix }}',
    deleteText: "<div class='btn btn-danger btn-circle'><i class='fas fa-trash'></i></div>",
    addText: "<div class='btn btn-success btn-circle'><i class='fas fa-plus'></i></div>"
    }
  )
</script>
{% endblock content %}

templates/keuangan/tagihan_list.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Keuangan{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Tagihan</li>
<li><i class="fa fa-laptop"></i>List</li>
{% endblock breadcrumb %}

{% block heading %}
Pembayaran {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<div class="table-responsive">
    <a href="{% url 'uang:tagihan-baru' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Buat Invoice Baru</a>
    <a href="#" class="btn btn-success"><i class="fa fa-plus"></i> Buat Semua Invoice</a>
    <table id="tabelinv" class="table table-striped table-hover table-advance">
        <thead>
            <tr>
                <th>S/N</th>
                <th>Nama / Kelas</th>
                <th>Tahun / Semester</th>
                <th>Harus Dibayar</th>
                <th>Sudah Dibayar</th>
                <th>Belum Dibayar</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for inv in object_list %}
            <tr class="clickable-row" data-href="{% url 'uang:tagihan-detail' inv.id %}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'uang:ttd-edit' pk=inv.id %}">{{ inv.murid }}</a> / {{ inv.untuk_kelas }}</td>
                <td>{{ inv.tahun }} / {{ inv.smester }}</td>
                <td>{{ inv.total_harus_dibayar }}</td>
                <td>{{ inv.jumlah_total_dibayar }}</td>
                <td>{{ inv.balance }}</td>
                {% if inv.status == 'lunas' %}
                <td><a class="btn btn-primary btn-sm">LUNAS</a></td>
                {% else %}
                <td><a class="btn btn-success btn-sm" href="{% url 'uang:tanda-terima' %}?pk={{ inv.id }}">Tanda Terima Baru</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    $('#tabelinv').DataTable({
    });
</script>
{% endblock content %}

templates/keuangan/tandaterima_form.html
{% extends 'html.html' %}
{% load widget_tweaks %}

{% block page_title %}{% block title %}Tanda Terima{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Tanda</li>
<li><i class="fa fa-laptop"></i>Terima</li>
{% endblock breadcrumb %}

{% block heading %}
Terima Pembayaran {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<div class="row">
    <div class="col-sm-8">
        <form method="post">
            {% csrf_token %}
            {% for f in form %}
            <div class="form-group">
                {{ f | add_label_class:"control-label" }}
                <div class="form-group">
                    {{ f | add_class:"form-control" | safe }}
                    {{ f.help_text }}
                </div>
                {% if f.errors %}
                <div class="form-group"><i class="far fa-times-circle"></i>{{ f.errors }}</div>
                {% endif %}
            </div>
            {% endfor %}
            {% if object %}
            <input type="submit" class="btn btn-primary" value="Update data">
            {% else %}
            <input type="submit" class="btn btn-primary" value="Save">
            {% endif %}
        </form>
    </div>

    <div class="col-sm-4">
        <div class="alert alert-info" role="alert">
            <h3>Ringkasan Pembayaran</h3>
            {{ tagihan | upper }}
            <hr>
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <td>Tahun</td>
                        <td>{{ tagihan.tahun }}</td>
                    </tr>
                    <tr>
                        <td>Semester</td>
                        <td>{{ tagihan.smester }}</td>
                    </tr>
                    <tr>
                        <td>Kelas</td>
                        <td>{{ tagihan.untuk_kelas }}</td>
                    </tr>
                    <tr>
                        <td>Semua Biaya</td>
                        <td>{{ tagihan.total_harus_dibayar }}</td>
                    </tr>
                    <tr>
                        <td>Sudah dibayar</td>
                        <td>{{ tagihan.jumlah_total_dibayar }}</td>
                    </tr>
                    <tr>
                        <td>Belum dibayar</td>
                        <td>{{ tagihan.balance }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}