adm_sekolah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('utama.urls')),
    path('siswa/', include('siswa.urls')),
    path('tagihan/', include('keuangan.urls')),
]

if settings.DEBUG :
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

keuangan/urls.py
from django.urls import path
from . import views

app_name = 'uang'
urlpatterns = [
    path('baru/', views.TagihanBaru.as_view(), name='tagihan-baru'),
    path('detail/<int:pk>/', views.TagihanDetail.as_view(), name='tagihan-detail'),
    path('delete/<int:pk>/', views.TagihanHapus.as_view(), name='tagihan-delete'),
    path('tanda-terima/', views.TandaTerimaAdd.as_view(), name='tanda-terima'),
    path('tanda-terima/edit/<int:pk>', views.TagihanEdit.as_view(), name='ttd-edit'),
    path('', views.TagihanView.as_view(), name='index'),
]

siswa/urls.py
from django.urls import path

from . import views

app_name = 'siswa'

urlpatterns = [
    path('baru/', views.SiswaAdd.as_view(), name='baru'),
    path('update/<int:pk>/', views.SiswaEdit.as_view(), name='update'),
    path('detail/<int:pk>/', views.SiswaDetail.as_view(), name='detail'),
    path('', views.SiswaList.as_view(), name='murid'),
]

utama/urls.py
from django.urls import path

from . import views

app_name = 'utama'
urlpatterns = [
    path('dev/', views.developer, name='dev'),
    path('setting/tahun-pelajaran/', views.TahunPelajaranView.as_view(), name='ta-list'),
    path('setting/tahun-pelajaran/add/', views.TahunPelajaranAdd.as_view(), name='ta-add'),
    path('setting/tahun-pelajaran/<int:pk>/edit/', views.TahunPelajaranEdit.as_view(), name='ta-edit'),
    path('setting/tahun-pelajaran/<int:pk>/del/', views.TahunPelajaranDel.as_view(), name='ta-del'),
    path('setting/semester/', views.SemesterView.as_view(), name='smt-list'),
    path('setting/semester/add/', views.SemesterAdd.as_view(), name='smt-add'),
    path('setting/semester/<int:pk>/edit/', views.SemesterEdit.as_view(), name='smt-edit'),
    path('setting/semester/<int:pk>/del/', views.SemesterDel.as_view(), name='smt-del'),
    path('setting/kelas/', views.KelasView.as_view(), name='kls-list'),
    path('setting/kelas/add/', views.KelasAdd.as_view(), name='kls-add'),
    path('setting/kelas/<int:pk>/edit/', views.KelasEdit.as_view(), name='kls-edit'),
    path('setting/kelas/<int:pk>/del/', views.KelasDel.as_view(), name='kls-del'),
    path('setting/mapel/', views.MapelView.as_view(), name='mpl-list'),
    path('setting/mapel/add/', views.MapelAdd.as_view(), name='mpl-add'),
    path('setting/mapel/<int:pk>/edit/', views.MapelEdit.as_view(), name='mpl-edit'),
    path('setting/mapel/<int:pk>/del/', views.MapelDel.as_view(), name='mpl-del'),
    path('setting/biaya/', views.BiayaMasuk.as_view(), name='biaya'),
    path('setting/biaya/pendaftaran/', views.BiayaAdd.as_view(), name='bi-add'),
    path('setting/biaya/<int:pk>/edit/', views.BiayaEdit.as_view(), name='bi-edit'),
    path('', views.index_utama, name='index'),
]

templates/base/header.html
{% load static %}

<header class="header dark-bg">
    <div class="toggle-nav">
      <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
    </div>

    <!--logo start-->
    <a href="{% url 'utama:dev' %}" class="logo m-auto"><img src="{% static 'img/smk1.png' %}" class="rounded mx-auto d-block" style="width: 40px;" alt="SMKN 1 Banjar"></a>
    <!--logo end-->

    <div class="nav search-row" id="top_menu">
      <!--  search form start -->
      <ul class="nav top-menu">
        <li>
          <form class="navbar-form">
            <input class="form-control" placeholder="Search" type="text">
          </form>
        </li>
      </ul>
      <!--  search form end -->
    </div>

    {% comment %} <div class="top-nav notification-row">
      <!-- notificatoin dropdown start-->
      <ul class="nav pull-right top-menu">

        <!-- task notificatoin start -->
        <li id="task_notificatoin_bar" class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <i class="icon-task-l"></i>
                          <span class="badge bg-important">6</span>
                      </a>
          <ul class="dropdown-menu extended tasks-bar">
            <div class="notify-arrow notify-arrow-blue"></div>
            <li>
              <p class="blue">You have 6 pending letter</p>
            </li>
            <li>
              <a href="#">
                <div class="task-info">
                  <div class="desc">Design PSD </div>
                  <div class="percent">90%</div>
                </div>
                <div class="progress progress-striped">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                    <span class="sr-only">90% Complete (success)</span>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <a href="#">
                <div class="task-info">
                  <div class="desc">
                    Project 1
                  </div>
                  <div class="percent">30%</div>
                </div>
                <div class="progress progress-striped">
                  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%">
                    <span class="sr-only">30% Complete (warning)</span>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <a href="#">
                <div class="task-info">
                  <div class="desc">Digital Marketing</div>
                  <div class="percent">80%</div>
                </div>
                <div class="progress progress-striped">
                  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                    <span class="sr-only">80% Complete</span>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <a href="#">
                <div class="task-info">
                  <div class="desc">Logo Designing</div>
                  <div class="percent">78%</div>
                </div>
                <div class="progress progress-striped">
                  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100" style="width: 78%">
                    <span class="sr-only">78% Complete (danger)</span>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <a href="#">
                <div class="task-info">
                  <div class="desc">Mobile App</div>
                  <div class="percent">50%</div>
                </div>
                <div class="progress progress-striped active">
                  <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                    <span class="sr-only">50% Complete</span>
                  </div>
                </div>

              </a>
            </li>
            <li class="external">
              <a href="#">See All Tasks</a>
            </li>
          </ul>
        </li>
        <!-- task notificatoin end -->
        <!-- inbox notificatoin start-->
        <li id="mail_notificatoin_bar" class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <i class="icon-envelope-l"></i>
                          <span class="badge bg-important">5</span>
                      </a>
          <ul class="dropdown-menu extended inbox">
            <div class="notify-arrow notify-arrow-blue"></div>
            <li>
              <p class="blue">You have 5 new messages</p>
            </li>
            <li>
              <a href="#">
                                  <span class="photo"><img alt="avatar" src="./img/avatar-mini.jpg"></span>
                                  <span class="subject">
                                  <span class="from">Greg  Martin</span>
                                  <span class="time">1 min</span>
                                  </span>
                                  <span class="message">
                                      I really like this admin panel.
                                  </span>
                              </a>
            </li>
            <li>
              <a href="#">
                                  <span class="photo"><img alt="avatar" src="./img/avatar-mini2.jpg"></span>
                                  <span class="subject">
                                  <span class="from">Bob   Mckenzie</span>
                                  <span class="time">5 mins</span>
                                  </span>
                                  <span class="message">
                                   Hi, What is next project plan?
                                  </span>
                              </a>
            </li>
            <li>
              <a href="#">
                                  <span class="photo"><img alt="avatar" src="./img/avatar-mini3.jpg"></span>
                                  <span class="subject">
                                  <span class="from">Phillip   Park</span>
                                  <span class="time">2 hrs</span>
                                  </span>
                                  <span class="message">
                                      I am like to buy this Admin Template.
                                  </span>
                              </a>
            </li>
            <li>
              <a href="#">
                                  <span class="photo"><img alt="avatar" src="./img/avatar-mini4.jpg"></span>
                                  <span class="subject">
                                  <span class="from">Ray   Munoz</span>
                                  <span class="time">1 day</span>
                                  </span>
                                  <span class="message">
                                      Icon fonts are great.
                                  </span>
                              </a>
            </li>
            <li>
              <a href="#">See all messages</a>
            </li>
          </ul>
        </li>
        <!-- inbox notificatoin end -->
        <!-- alert notification start-->
        <li id="alert_notificatoin_bar" class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                          <i class="icon-bell-l"></i>
                          <span class="badge bg-important">7</span>
                      </a>
          <ul class="dropdown-menu extended notification">
            <div class="notify-arrow notify-arrow-blue"></div>
            <li>
              <p class="blue">You have 4 new notifications</p>
            </li>
            <li>
              <a href="#">
                                  <span class="label label-primary"><i class="icon_profile"></i></span>
                                  Friend Request
                                  <span class="small italic pull-right">5 mins</span>
                              </a>
            </li>
            <li>
              <a href="#">
                                  <span class="label label-warning"><i class="icon_pin"></i></span>
                                  John location.
                                  <span class="small italic pull-right">50 mins</span>
                              </a>
            </li>
            <li>
              <a href="#">
                                  <span class="label label-danger"><i class="icon_book_alt"></i></span>
                                  Project 3 Completed.
                                  <span class="small italic pull-right">1 hr</span>
                              </a>
            </li>
            <li>
              <a href="#">
                                  <span class="label label-success"><i class="icon_like"></i></span>
                                  Mick appreciated your work.
                                  <span class="small italic pull-right"> Today</span>
                              </a>
            </li>
            <li>
              <a href="#">See all notifications</a>
            </li>
          </ul>
        </li>
        <!-- alert notification end-->
        <!-- user login dropdown start-->
        <li class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <span class="profile-ava">
                              <img alt="" src="img/avatar1_small.jpg">
                          </span>
                          <span class="username">Jenifer Smith</span>
                          <b class="caret"></b>
                      </a>
          <ul class="dropdown-menu extended logout">
            <div class="log-arrow-up"></div>
            <li class="eborder-top">
              <a href="#"><i class="icon_profile"></i> My Profile</a>
            </li>
            <li>
              <a href="#"><i class="icon_mail_alt"></i> My Inbox</a>
            </li>
            <li>
              <a href="#"><i class="icon_clock_alt"></i> Timeline</a>
            </li>
            <li>
              <a href="#"><i class="icon_chat_alt"></i> Chats</a>
            </li>
            <li>
              <a href="#"><i class="icon_key_alt"></i> Log Out</a>
            </li>
            <li>
              <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
            </li>
            <li>
              <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
            </li>
          </ul>
        </li>
        <!-- user login dropdown end -->
      </ul>
      <!-- notificatoin dropdown end-->
    </div> {% endcomment %}
  </header>
  <!--header end-->

templates/base/js.html
{% load static %}
<!-- javascripts -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}"></script>
<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- nice scroll -->
<script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
<!-- charts scripts -->
<script src="{% static 'assets/jquery-knob/js/jquery.knob.js' %}"></script>
<script src="{% static 'js/jquery.sparkline.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js' %}"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
<!-- jQuery full calendar -->
<script src="{% static 'js/fullcalendar.min.js' %}"></script>
  <!-- Full Google Calendar - Calendar -->
  <script src="{% static 'assets/fullcalendar/fullcalendar/fullcalendar.js' %}"></script>
  <!--script for this page only-->
  <script src="{% static 'js/calendar-custom.js' %}"></script>
  <script src="{% static 'js/jquery.rateit.min.js' %}"></script>
  <!-- custom select -->
  <script src="{% static 'js/jquery.customSelect.min.js' %}"></script>
  <script src="{% static 'assets/chart-master/Chart.js' %}"></script>

  <!--custome script for all page-->
  <script src="{% static 'js/scripts.js' %}"></script>
  <!-- custom script for this page-->
  <script src="{% static 'js/sparkline-chart.js' %}"></script>
  <script src="{% static 'js/easy-pie-chart.js' %}"></script>
  <script src="{% static 'js/jquery-jvectormap-1.2.2.min.js' %}"></script>
  <script src="{% static 'js/jquery-jvectormap-world-mill-en.js' %}"></script>
  <script src="{% static 'js/xcharts.min.js' %}"></script>
  <script src="{% static 'js/jquery.autosize.min.js' %}"></script>
  <script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
  <script src="{% static 'js/gdp-data.js' %}"></script>
  <script src="{% static 'js/morris.min.js' %}"></script>
  <script src="{% static 'js/sparklines.js' %}"></script>
  <script src="{% static 'js/charts.js' %}"></script>
  <script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>
  <script>
    //knob
    $(function() {
      $(".knob").knob({
        'draw': function() {
          $(this.i).val(this.cv + '%')
        }
      })
    });

    //carousel
    $(document).ready(function() {
      $("#owl-slider").owlCarousel({
        navigation: true,
        slideSpeed: 300,
        paginationSpeed: 400,
        singleItem: true

      });
    });

    //custom select box

    $(function() {
      $('select.styled').customSelect();
    });

    /* ---------- Map ---------- */
    $(function() {
      $('#map').vectorMap({
        map: 'world_mill_en',
        series: {
          regions: [{
            values: gdpData,
            scale: ['#000', '#000'],
            normalizeFunction: 'polynomial'
          }]
        },
        backgroundColor: '#eef3f7',
        onLabelShow: function(e, el, code) {
          el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
        }
      });
    });
  </script>
<script src="{% static 'assets/DataTables/datatables.min.js' %}"></script>

<script>
  (function ($) {
    $('.clickable-row').css('cursor', 'pointer');
    $(".clickable-row").click(function () {
      window.location = $(this).data("href");
    });
  })(jQuery)

</script>

templates/base/sidebar.html
    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li class="active">
            <a class="" href="{% url 'utama:dev' %}">
                          <i class="icon_house_alt"></i>
                          <span>Dashboard</span>
                      </a>
          </li>
          <li class="sub-menu">
            <a href="javascript:;" class="">
                          <i class="fa fa-cogs"></i>
                          <span>Setting</span>
                          <span class="menu-arrow arrow_carrot-right"></span>
                      </a>
            <ul class="sub">
              <li><a class="" href="{% url 'utama:biaya' %}"><span>Biaya Masuk</span></a></li>
              <li><a class="" href="{% url 'utama:kls-list' %}"><span>Kelas</span></a></li>
              <li><a class="" href="{% url 'utama:smt-list' %}"><span>Semester</span></a></li>
              <li><a class="" href="{% url 'utama:ta-list' %}">Tahun Pelajaran</a></li>
            </ul>
          </li>
          <li>
            <a class="" href="{% url 'utama:mpl-list' %}">
                          <i class="fa fa-book"></i>
                          <span>Mata Pelajaran</span>  
                      </a>
          </li>
          <li>
            <a class="" href="{% url 'uang:index' %}">
                          <i class="fa fa-money"></i>
                          <span>Keuangan</span>  
                      </a>
          </li>
          <li>
            <a class="" href="{% url 'siswa:murid' %}">
                          <i class="fa fa-users"></i>
                          <span>Siswa</span>  
                      </a>
          </li>
          <li>
            <a class="" href="">
                          <i class="fa fa-empire"></i>
                          <span>Karyawan</span>
                      </a>
          </li>
          <li>
            <a class="" href="#">
                          <i class="fa fa-code"></i>
                          <span>Pengembang</span>  
                      </a>
          </li>
          <li>
            <a class="" href="{% url 'logout' %}">
                          <i class="fa fa-sign-out"></i>
                          <span>Log out</span>

                      </a>
          </li>  
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

templates/base/style.html
{% load static %}
<!-- Bootstrap CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<!-- bootstrap theme -->
<link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
<!--external css-->
<!-- font icon -->
<link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
<!-- full calendar css-->
<link href="{% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
<link href="{% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
<!-- easy pie chart-->
<link href="{% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
<!-- owl carousel -->
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
<link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
<!-- Custom styles -->
<link href="{% static 'css/fullcalendar.css' %}" rel="stylesheet" >
<link href="{% static 'css/widgets.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
<link href="{% static 'css/xcharts.min.css' %}" rel=" stylesheet">
<link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
<!-- =======================================================
  Theme Name: NiceAdmin
  Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  Author: BootstrapMade
  Author URL: https://bootstrapmade.com
======================================================= -->