adm_sekolah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('utama.urls')),
    path('siswa/', include('siswa.urls')),
    path('tagihan/', include('keuangan.urls')),
]

if settings.DEBUG :
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siswa/urls.py
from django.urls import path

from . import views

app_name = 'siswa'

urlpatterns = [
    path('baru/', views.SiswaAdd.as_view(), name='baru'),
    path('update/<int:pk>/', views.SiswaEdit.as_view(), name='update'),
    path('detail/<int:pk>/', views.SiswaDetail.as_view(), name='detail'),
    path('', views.SiswaList.as_view(), name='murid'),
]

siswa/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse
from utama.models import Kelas, Mapel

# Create your models here.
class Siswa(models.Model):
    STATUS = {
        ('aktif', 'Aktif'),
        ('lulus', 'Lulus'),
        ('do', 'Drop Out'),
    }
    GENDER = {
        ('pria', 'Pria'),
        ('wanita', 'Wanita')
    }
    
    status = models.CharField(choices=STATUS, max_length=20, default='Aktif')
    nomor_pendaftaran = models.CharField(max_length=50, unique=True)
    nama = models.CharField(max_length=200)
    nama_panggilan = models.CharField(max_length=200, blank=True, null=True)
    gender = models.CharField(choices=GENDER, max_length=30)
    tanggal_lahir = models.DateField()
    kelas_sekarang = models.ForeignKey(Kelas, on_delete=models.SET_NULL, null=True, blank=True)
    tanggal_daftar = models.DateField(auto_now_add=True)
    hp_regex = RegexValidator(regex='^[0-9]{10-15}$', message='Hp tidak sesuai')
    hp_orang_tua = models.CharField(validators=[hp_regex], max_length=15, blank=True, null=True)
    alamat = models.TextField(blank=True)
    keterangan = models.TextField(blank=True)
    photo = models.ImageField(upload_to='siswa/photo', blank=True, null=True)
    
    class Meta:
        ordering = ['nama', 'nomor_pendaftaran']
        
    def __str__(self):
        return self.nama
    
    def get_absolute_url(self):
        return reverse('siswa:detail', kwargs={'pk' : self.pk})
    

siswa/forms.py
from django import forms
from django.forms import ModelForm
from .models import Siswa

class SiswaForm(ModelForm):
    prefix = 'siswa'
    class Meta:
        model = Siswa
        fields = '__all__'
        widgets = {
            'tanggal_lahir': forms.DateInput(
                attrs={
                    'type': 'date'
                }
            ),
            'alamat': forms.Textarea(
                attrs={
                    'rows': '2'
                }
            ),
            'keterangan': forms.Textarea(
                attrs={
                    'rows': '2'
                }
            ),
        }

siswa/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Siswa
from keuangan.models import Tagihan
from .forms import SiswaForm

# Create your views here.
class SiswaList(LoginRequiredMixin, ListView):
    queryset = Siswa.objects.all()

class SiswaAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = SiswaForm
    success_message = 'Siswa baru terdaftar'
    success_url = reverse_lazy('siswa:murid')
    template_name = 'utama/form_utama.html'
    extra_context = {
        'title': 'Pendaftaran Siswa'
    }

class SiswaEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    queryset = Siswa.objects.all()
    form_class = SiswaForm
    success_message = 'Siswa berhasil diupdate'
    success_url = reverse_lazy('siswa:murid')
    template_name = 'utama/form_utama.html'
    extra_context = {
        'title': 'Update Siswa'
    }

class SiswaDetail(LoginRequiredMixin, DetailView):
    queryset = Siswa.objects.all()

    def get_context_data(self, **kwargs):
        context = super(SiswaDetail, self).get_context_data(**kwargs)
        context['pembayaran'] = Tagihan.objects.filter(murid=self.object)
        return context

templates/siswa/siswa_detail.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Siswa {{ object.nama }}{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Siswa</li>
<li><i class="fa fa-laptop"></i>{{ object.nama }}</li>
{% endblock breadcrumb %}

{% block heading %}
Data {{ object.nama }} {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="profile-widget profile-widget-info">
            <div class="panel-body">
                <div class="col-lg-2 col-sm-2">
                    <h4>{{ object.nama }}</h4>
                    <div class="follow-ava">
                        {% if object.photo %}
                        <img src="{{ object.photo.url }}" alt="{{ object.nama }}"/>
                        {% endif %}
                    </div>
                    <h6>{{ object.nomor_pendaftaran }}</h6>
                </div>
                <div class="col-lg-4 col-sm-4 follow-info">
                    <p><strong>Kelas : </strong>{{ object.kelas_sekarang }} <strong>Status </strong>: {{ object.status }}</p>
                    <p><strong>Alamat : {{ object.alamat }}</strong></p>
                    <p><strong>Keterangan : </strong>{{ object.keterangan }}</p>
                </div>
                <div class="col-lg-2 col-sm-6 follow-info weather-category">
                    <ul>
                        <li class="active">
                            <a href="#" class="btn btn-success" ><i class="fa fa-print fa-2x"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-sm-6 follow-info weather-category">
                    <ul>
                        <li class="active">
                            <a href="{% url 'siswa:update' object.id %}" class="btn btn-primary"><i class="fa fa-pencil fa-2x"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-sm-6 follow-info weather-category">
                    <ul>
                        <li class="active">
                            <a href="#" class="btn btn-danger"><i class="fa fa-trash-o fa-2x"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading tab-bg-info">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a data-toggle="tab" href="#pembayaran">
                                <i class="fa fa-money"></i>Riwayat Pembayaran
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#profile">
                                <i class="fa fa-user"></i>Profil
                            </a>
                        </li>
                    </ul>
                </header>
                <div class="panel-body">
                    <div class="tab-content">
                        <div id="pembayaran" class="tab-pane active">
                            <div class="profile-activity">
                                <div class="act-time">
                                    <div class="activity-body act-in">
                                        <span class="arrow"></span>
                                        <div class="text">
                                            <h4>Riwayat Pembayaran</h4>
                                            {% if pembayaran %}
                                            <table class="table table-hover table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Untuk</th>
                                                        <th>Jumlah Tagihan</th>
                                                        <th>Sudah Dibayar</th>
                                                        <th>Balance</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for bayar in pembayaran %}
                                                    <tr class="clickable-row" data-href="#">
                                                        <td>{{ bayar.tahun }} {{ bayar.smester }} {{ bayar.untuk_kelas }}</td>
                                                        <td>{{ bayar.total_harus_dibayar }}</td>
                                                        <td>{{ bayar.jumlah_total_dibayar }}</td>
                                                        <td>{{ bayar.balance }}</td>
                                                    </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                            {% else %}
                                            <p>Belum ada riwayat pembayaran dari {{ object.name }}</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="profile" class="tab-pane">
                            <section class="panel">
                                <div class="bio-graph-heading">
                                    {{ object.nama }} {{ object.kelas_sekarang }}
                                </div>
                                <div class="panel-body bio-graph-info">
                                    <h1>Bio Graph</h1>
                                    <div class="row">
                                        <div class="bio-brow">
                                            {% if object.poto %}
                                            <p><img src="{{ object.poto.url }}"/></p>
                                            {% endif %}
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Nama </span>: {{ object.nama }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Nama Panggilan</span>: {{ object.nama_panggilan }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Kelas</span>: {{ object.kelas_sekarang }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Tanggal Lahir</span>: {{ object.tanggal_lahir }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Gender</span>: {{ object.gender }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Alamat</span>: {{ object.alamat }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>HP Orang Tua/Wali</span>: {{ object.hp_orang_tua }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Nomor Pendaftaran</span>: {{ object.nomor_pendaftaran }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Tanggal Daftar</span>: {{ object.tanggal_daftar }}</p>
                                        </div>
                                        <div class="bio-brow">
                                            <p><span>Keterangan</span>: {{ object.keterangan }}</p>
                                        </div>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock content %}

templates/siswa/siswa_list.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Daftar Semua Siswa{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Siswa</li>
<li><i class="fa fa-laptop"></i>Semua</li>
{% endblock breadcrumb %}

{% block heading %}
Semua Siswa {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<table id="tabelsiswa" class="table table-striped table-advance table-hover">
    <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr class="clickable-row" data-href="{% url 'siswa:detail' object.id %}">
            <td>{{ object }}</td>
            <td>
                <a href="{% url 'siswa:baru' %}" class="btn btn-primary"><i class="icon_plus_alt2"></i></a>
                <a href="{% url 'siswa:update' object.id %}" class="btn btn-success"><i class="fa fa-edit"></i></a> 
                <a href="#" class="btn btn-danger"><i class="icon_close_alt2"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td><h2>Belum ada siswa terdaftar</h2></td>
            <td><a href="{% url 'siswa:baru' %}">Buat baru</a></td>
        </tr>
        {% endif %}
    </tbody>
</table>

<script>
    $('#tabelsiswa').DataTable({
    });
</script>
{% endblock content %}